export const languages = [
  { code: 'en', name: 'English', native: 'English', country: '🇺🇸' },
  { code: 'bn', name: 'Bangla', native: 'বাংলা', country: '🇧🇩' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', country: '🇮🇳' },
  { code: 'ur', name: 'Urdu', native: 'اردو', country: '🇵🇰' },
  { code: 'ar', name: 'Arabic', native: 'العربية', country: '🇸🇦' },
  { code: 'es', name: 'Spanish', native: 'Español', country: '🇪🇸' },
  { code: 'fr', name: 'French', native: 'Français', country: '🇫🇷' },
  { code: 'de', name: 'German', native: 'Deutsch', country: '🇩🇪' },
  { code: 'pt', name: 'Portuguese', native: 'Português', country: '🇧🇷' },
  { code: 'ru', name: 'Russian', native: 'Русский', country: '🇷🇺' },
  { code: 'tr', name: 'Turkish', native: 'Türkçe', country: '🇹🇷' },
  { code: 'id', name: 'Indonesian', native: 'Bahasa Indonesia', country: '🇮🇩' },
  { code: 'ms', name: 'Malay', native: 'Melayu', country: '🇲🇾' },
  { code: 'th', name: 'Thai', native: 'ไทย', country: '🇹🇭' },
  { code: 'vi', name: 'Vietnamese', native: 'Tiếng Việt', country: '🇻🇳' },
  { code: 'ja', name: 'Japanese', native: '日本語', country: '🇯🇵' },
  { code: 'ko', name: 'Korean', native: '한국어', country: '🇰🇷' },
  { code: 'zh', name: 'Chinese', native: '中文', country: '🇨🇳' },
  { code: 'tw', name: 'Chinese Traditional', native: '繁體中文', country: '🇹🇼' },
  { code: 'it', name: 'Italian', native: 'Italiano', country: '🇮🇹' },
  { code: 'nl', name: 'Dutch', native: 'Nederlands', country: '🇳🇱' },
  { code: 'pl', name: 'Polish', native: 'Polski', country: '🇵🇱' },
  { code: 'uk', name: 'Ukrainian', native: 'Українська', country: '🇺🇦' },
  { code: 'fa', name: 'Persian', native: 'فارسی', country: '🇮🇷' },
  { code: 'ps', name: 'Pashto', native: 'پښتو', country: '🇦🇫' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', country: '🇱🇰' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', country: '🇮🇳' },
  { code: 'mr', name: 'Marathi', native: 'मराठी', country: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી', country: '🇮🇳' },
  { code: 'fil', name: 'Filipino', native: 'Filipino', country: '🇵🇭' },
];

export const translations: any = {
  en: { for_you: 'For You', following: 'Following', live: 'LIVE' },
  bn: { for_you: 'আপনার জন্য', following: 'ফলোয়িং', live: 'লাইভ' },
  hi: { for_you: 'आपके लिए', following: 'फॉलोइंग', live: 'लाइव' },
  ur: { for_you: 'آپ کے لیے', following: 'فالونگ', live: 'لائیو' },
  ar: { for_you: 'لك', following: 'أتابع', live: 'مباشر' },
};